### ISSUE TITLE
java.lang.NullPointerException at io.github.sleroy.sonar.EsLintSensor.execute(EsLintSensor.java:121)

### ISSUE THREAD

**Issue by emexelem** [sleroy/SonarEsLintPlugin#11]
The issue is similar to https://github.com/sleroy/SonarEsLintPlugin/issues/2

I'm running sonar scanner from jenkins or command line (same issue with both) with this config file:
sonar.projectKey=project
sonar.projectName=project
sonar.projectVersion=0.1
sonar.sources=.
sonar.inclusions=src/**
sonar.scm.provider=git
sonar.eslint.reportPaths=eslint-report.json
sonar.host.url=https://sonar.domain.com
sonar.login=blabla

eslint-report.json does exist and has valid json data. It has been produced by eslint with json output format.

```
13:20:21.765 DEBUG: Executing EsLint with command: node J:\wks\fa723ab7\node_modules\eslint\bin\eslint.js -f json --output-file J:\wks\fa723ab7\.scannerwork\.sonartmp\5493670960467370263.tmp --config J:\wks\fa723ab7\.eslintrc.json J:/wks/fa723ab7/src/Project/code/Scripts/components/tile/tile-item.vue etc
13:20:25.192 INFO: ------------------------------------------------------------------------
13:20:25.195 INFO: EXECUTION FAILURE
13:20:25.195 INFO: ------------------------------------------------------------------------
13:20:25.195 INFO: Total time: 54.270s
13:20:25.285 INFO: Final Memory: 35M/1373M
13:20:25.285 INFO: ------------------------------------------------------------------------
13:20:25.285 ERROR: Error during SonarQube Scanner execution
java.lang.NullPointerException
        at io.github.sleroy.sonar.EsLintSensor.execute(EsLintSensor.java:121)
        at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:45)
```

I don't understand why sonar-scanner still tries to run eslint as i provided the report file in the config file, it should just import the result no?
I tried with or without the sonar.eslint.reportPaths and i get NPE in both cases.

Sonar scanner version is 3.2.0.1227

**Comment by emexelem** [comment]
Working fine with eslint plugin v0.3.0 (had to install it manually though, not visible in sonarqube update center).
Sorry for the noise

**Comment by sleroy** [comment]
SonarQube marketplace will never accept this plugin.
