### ISSUE TITLE
Please add link to SonarJS documentation

### ISSUE THREAD

**Issue by thomaspeklak** [sleroy/SonarEsLintPlugin#13]
It seems that SonarJS now supports the import of an eslint result.json:
https://docs.sonarqube.org/display/PLUG/Importing+ESLint+Issues+Reports

I don't know if you want to maintain this plugin further, but it does not seem so. You could help people find the their way to this solution.

**Comment by sleroy** [comment]
Indeed, I will deprecate the plugin now. Thank you for the notice.
