### ISSUE TITLE
ESLint plugin is embedded with a profile containing 0 rules

### ISSUE THREAD

**Issue by michellechsy** [sleroy/SonarEsLintPlugin#21]
![image](https://user-images.githubusercontent.com/7827768/101467136-e83d6e00-397c-11eb-8861-1bef213470a1.png)

(A bit new to this with Sonar) When I added this plugin into my Sonar server and set the sonar-project.properties to point to the eslint inside my project, I found the sonar mentioned no rules for the eslint profile when executing sonar analysis. 
Questions:
1. Did I missed any configuration? I'm using monorepo for my UI/API project, but I have set separate sonar properties file in each project.  
2. I can see there are 300+ rules of ESlint when checked from Sonar Admin, why it said no rules? 
3. If I use the `Sonar Way` profile, I can get lots of code smells, but if I changed to "EsLint" in the "Quality Profile", no code smells found. I'm not quite sure if it's correct behavior.. We do have eslint checking in our project for every code commit to restrict the ESLint styles, so when integrate with Sonar, I'm not quite sure which one I should refer to :(

**Comment by sleroy** [comment]
Hi Michelle,

If you are using the new version of SonarQube (> 7.2), the eslint 
violation report can be imported directly from the original Sonar 
Javascript plugin.

You do not need my plugin in this case.

https://docs.sonarqube.org/pages/viewpage.action?pageId=11639183


Best regards,

Sylvain

Le 08.12.20 à 10:50, Michelle a écrit :

**Comment by michellechsy** [comment]
Oh, that's cool. Let me try with that then. Thanks Sleroy!
