### ISSUE TITLE
Unable to locate Jar file for Release 0.3.0

### ISSUE THREAD

**Issue by codingmkd** [sleroy/SonarEsLintPlugin#4]
I could not find jar file on  new release 0.3.0 @ https://github.com/sleroy/SonarEsLintPlugin/releases
can you please give location  for new Jar file if any

**Comment by sleroy** [comment]
I will fix it now

**Comment by sleroy** [comment]
Uploaded : https://github.com/sleroy/SonarEsLintPlugin/releases/tag/release-0.3.0
